### ISSUE TITLE
Put extension before answers to "Question"

### ISSUE THREAD

**Issue by Nesquickforce** [khoi-nguyen/notes#2]
Find way to put Extension questions before the answers to "Question" come up - practical issue during lesson.

**Comment by khoi-nguyen** [comment]
https://github.com/khoi-nguyen/notes/commit/afe2dea5f29107f2f05b431a683cf72737eaec23

Should solve the issue

**Comment by Nesquickforce** [comment]
`---
title: Indices
subtitle: Multiplying with indices
...

# Starter

::: Starter
Evaluate the following:

#) `mult('a^2', a=3)`
#) `mult('a^2', a=5)`
#) `mult('a^2', a=8)`
#) `mult('a^1', a=7)`
:::

# Indices

::: Exercise
Simplify the following indices:

#) `mult('a^4', 'a^7', a=3)`
#) `mult('a^2', 'a^6', a=10)`
#) `mult('a^4', 'a^-2', a=6)`
#) `mult('a^-3', 'a^-9', a=5)`
#) `mult('a', 'a^3', a=9)`
:::

::: {.Extension show=1}
Evaluate the following:

#) `mult('a^4', 'a^-4', a=10)`
#) $7^0$ [1]{.answer}
#) $x^0$ [1]{.answer}
:::`

**Comment by khoi-nguyen** [comment]
Works on my computer, so will close the issue, we'll see when you commit your slide.

**Comment by khoi-nguyen** [comment]
Maybe the default behaviour should be to display all the blocks, and only when this is done, start displaying the answer? @Nesquickforce
